# Generated by Django 5.0.6 on 2024-07-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100, null=True)),
                ('Religion', models.CharField(max_length=100, null=True)),
                ('civil_status', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('blood_type', models.CharField(max_length=100, null=True)),
                ('mothers_maiden_name', models.TextField(max_length=100)),
                ('mothers_ocupation', models.CharField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100, null=True)),
                ('StudentID', models.CharField(max_length=100, null=True)),
                ('year_level', models.TextField(max_length=100)),
                ('course_or_program', models.TextField(max_length=100)),
            ],
        ),
    ]
