# Generated by Django 5.0.6 on 2024-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='StudentID',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='item',
            name='course_or_program',
        ),
        migrations.RemoveField(
            model_name='item',
            name='year_level',
        ),
        migrations.AddField(
            model_name='item',
            name='elementary_school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='high_school',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
