# Generated by Django 5.0.6 on 2024-07-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_college_item_vocational_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vocational_course',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='father_name',
            new_name='father_fname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mothers_maiden_name',
            new_name='mothers_maiden_fname',
        ),
        migrations.AddField(
            model_name='item',
            name='father_sname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mothers_maiden_sname',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
