# Generated by Django 5.0.6 on 2024-07-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_vocational_course_item_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='father_fname',
            new_name='father_firstname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Religion',
            new_name='father_surname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mothers_maiden_fname',
            new_name='mothers_maiden_firstname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mothers_maiden_sname',
            new_name='mothers_maiden_surname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='father_sname',
            new_name='religion',
        ),
    ]
